// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Um-Iwwp_QyV_FDNjdPdnQiYxf_8ryb8',
    appId: '1:432994350725:web:114c4b00ec465d2c8f9bec',
    messagingSenderId: '432994350725',
    projectId: 'test-firebase-c8f86',
    authDomain: 'test-firebase-c8f86.firebaseapp.com',
    storageBucket: 'test-firebase-c8f86.appspot.com',
    measurementId: 'G-LGYL82F8YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO96ymSyVohMOjQ7f4lrdKT0ljO7NAH_w',
    appId: '1:432994350725:android:beeadf73ec35889a8f9bec',
    messagingSenderId: '432994350725',
    projectId: 'test-firebase-c8f86',
    storageBucket: 'test-firebase-c8f86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-FoR5-oOws0kYPb_ATqYOyug-lZeThJs',
    appId: '1:432994350725:ios:3d36623bab256c7f8f9bec',
    messagingSenderId: '432994350725',
    projectId: 'test-firebase-c8f86',
    storageBucket: 'test-firebase-c8f86.appspot.com',
    iosClientId: '432994350725-kor801d9tj8vlckt994mi6vli11uhs6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-FoR5-oOws0kYPb_ATqYOyug-lZeThJs',
    appId: '1:432994350725:ios:3d36623bab256c7f8f9bec',
    messagingSenderId: '432994350725',
    projectId: 'test-firebase-c8f86',
    storageBucket: 'test-firebase-c8f86.appspot.com',
    iosClientId: '432994350725-kor801d9tj8vlckt994mi6vli11uhs6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
